### PR TITLE
Update to 1.20.2

### PR DESCRIPTION
**Pull request by Pixaurora**
Hello! I found your mod a few days ago and wanted to try it out on the latest version, so I decided to go ahead and update it.

I might try making a unique background for the mod's toasts in a few days as well, since I noticed that in vanilla differently purposed toasts have different backgrounds as well!

### CODE REVIEW

**Comment by Scotsguy** [comment]
Woah, thanks! Please bump the patch version in gradle.properties. Looks good otherwise!

**Comment by Pixaurora** [comment]
Done!

**Comment by Scotsguy** [comment]
Just tested, works on both Fabric and LexForge (Quilt doesn't have a 1.20.2 release yet)

**Comment by Scotsguy** [comment]
Now up on Modrinth, GitHub and CurseForge will follow once CI runs. Cheers!

**Pull request merged**
