### PR TITLE
i18n: Add Chinese translation

### PR DESCRIPTION
**Pull request by user111192**
Add Chinese translation support
Create zh_cn.json

### CODE REVIEW

**Comment by NotRyken** [comment]
Please remove the `music` keys, since they aren't translated they should be allowed to fall back on the default localization. Once done this can be merged.

**Comment by user111192** [comment]
> Please remove the `music` keys, since they aren't translated they should be allowed to fall back on the default localization. Once done this can be merged.

done

**Comment by user111192** [comment]
@NotRyken Done.

**Comment by user111192** [comment]
@NotRyken I found a bug and fixed it in #46.

**Pull request merged**
