### PR TITLE
Added Japanese Translation

### PR DESCRIPTION
**Pull request by KAGUYA-1137**
Added ja_jp.json

### CODE REVIEW

**Comment by Scotsguy** [comment]
I can't test it right now, but I believe you can remove the song names from ja_jp.json and they'll automatically fall back to en_us.json. That way, they don't get duplicated unnecessarily.

**Comment by NotRyken** [comment]
> I can't test it right now, but I believe you can remove the song names from ja_jp.json and they'll automatically fall back to en_us.json. That way, they don't get duplicated unnecessarily.

Yes, that's correct.

**Comment by KAGUYA-1137** [comment]
> I can't test it right now, but I believe you can remove the song names from ja_jp.json and they'll automatically fall back to en_us.json. That way, they don't get duplicated unnecessarily.

Ok, removed the song names.

**Comment by NotRyken** [comment]
Apologies for the wait, I normally try to bundle translation updates with patches but in this case there hasn't been any. It's released now.

**Pull request merged**
